name: mkcert
description: mkcert command line tool for dart bash
version: 1.0.0

environment:
  sdk: '>=2.14.2 <3.0.0'


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  ffi: ^1.1.2
  ffigen: ^4.1.0

