name: mkcert
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.2 <3.0.0'


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  ffi: ^1.1.2
  ffigen: ^4.1.0

